# aa-exec
# Autogenerated from man page /usr/share/man/man1/aa-exec.1.gz
complete -c aa-exec -s p -l profile
complete -c aa-exec -s n -l namespace
complete -c aa-exec -s i -l immediate
complete -c aa-exec -s v -l verbose
complete -c aa-exec -s d -l debug

