# aa-enabled
# Autogenerated from man page /usr/share/man/man1/aa-enabled.1.gz
complete -c aa-enabled -s h -l help -d 'X Item "-h, --help" Display a brief usage guide'
complete -c aa-enabled -s q -l quiet -d 'X Item "-q, --quiet" Do not output anything to stdout'
complete -c aa-enabled -s x -l exclusive

