# aa-features-abi
# Autogenerated from man page /usr/share/man/man1/aa-features-abi.1.gz
complete -c aa-features-abi -s h -l help -d 'X Item "-h, --help" Display a brief usage guide'
complete -c aa-features-abi -s d -l debug -d 'X Item "-d, --debug" show messages with debugging information'
complete -c aa-features-abi -s v -l verbose
complete -c aa-features-abi -s x -l extract
complete -c aa-features-abi -s f -l file
complete -c aa-features-abi -l stdout
complete -c aa-features-abi -s w -l write

