# aa-remove-unknown
# Autogenerated from man page /usr/share/man/man8/aa-remove-unknown.8.gz
complete -c aa-remove-unknown -s h -l help -d 'X Item "-h, --help" displays a short usage statement'
complete -c aa-remove-unknown -s n

