# apparmor_parser
# Autogenerated from man page /usr/share/man/man8/apparmor_parser.8.gz
complete -c apparmor_parser -s B -l binary -d 'X Item "-B, --binary" Treat the profile files specified on the command line (…'
complete -c apparmor_parser -s C -l Complain -d 'X Item "-C, --Complain" Force the profile to load in complain mode'
complete -c apparmor_parser -s b -l base -d 'X Item "-b n, --base n" Set the base directory for resolving #include directi…'
complete -c apparmor_parser -s I -l Include -d 'X Item "-I n, --Include n" Add element n to the search path when resolving #i…'
complete -c apparmor_parser -s f -l apparmorfs -d 'X Item "-f n, --apparmorfs n" Set the location of the apparmor security files…'
complete -c apparmor_parser -l policy-features -d 'X Item "--policy-features n" Specify the feature set that the policy was deve…'
complete -c apparmor_parser -l override-policy-abi -d 'X Item "--override-policy-abi n" Specify the feature set that the policy was …'
complete -c apparmor_parser -l kernel-features -d 'X Item "--kernel-features n" Specify the feature set of the kernel that the p…'
complete -c apparmor_parser -s M -l features-file -d 'X Item "-M n, --features-file n" Use the features file located at path "n" (d…'
complete -c apparmor_parser -s m -l match-string -d 'X Item "-m n, --match-string n" Only use match features "n"'
complete -c apparmor_parser -s n -l namespace-string -d 'X Item "-n n, --namespace-string n" Force a profile to load in the namespace …'
complete -c apparmor_parser -s X -l readimpliesX -d 'X Item "-X, --readimpliesX" In the case of profiles that are loading on syste…'
complete -c apparmor_parser -s k -l show-cache -d 'X Item "-k, --show-cache" Report the cache processing (hit/miss details) when…'
complete -c apparmor_parser -s K -l skip-cache -d 'X Item "-K, --skip-cache" Perform no caching at all: disables -W, implies -T'
complete -c apparmor_parser -s T -l skip-read-cache -d 'X Item "-T, --skip-read-cache" By default, if a profile\'s cache is found in t…'
complete -c apparmor_parser -s W -l write-cache -d 'X Item "-W, --write-cache" Write out cached profiles to the location specifie…'
complete -c apparmor_parser -l skip-bad-cache -d 'X Item "--skip-bad-cache" Skip updating the cache if it contains cached profi…'
complete -c apparmor_parser -s L -l cache-loc -d 'X Item "-L, --cache-loc" Set the location(s) of the cache directory'
complete -c apparmor_parser -l print-cache-dir -d 'X Item "--print-cache-dir" Print the cache directory location'
complete -c apparmor_parser -s Q -l skip-kernel-load -d 'X Item "-Q, --skip-kernel-load" Perform all actions except the actual loading…'
complete -c apparmor_parser -s q -l quiet -d 'X Item "-q, --quiet" Do not report on the profiles as they are loaded, and no…'
complete -c apparmor_parser -s v -l verbose -d 'X Item "-v, --verbose" Report on the profiles as they are loaded, and show wa…'
complete -c apparmor_parser -l warn -d 'X Item "--warn=n" Enable various warnings during policy compilation'
complete -c apparmor_parser -l Werror -d 'X Item "--Werror[=n]" Convert warnings into errors during policy compilation'
complete -c apparmor_parser -s d -l debug -d 'X Item "-d, --debug" Given once, only checks the profiles to ensure syntactic…'
complete -c apparmor_parser -s D -l dump -d 'X Item "-D n, --dump=n" Debug flag for dumping various structures and passes …'
complete -c apparmor_parser -s j -l jobs -d 'X Item "-j n, --jobs=n" Set the number of jobs used to compile the specified …'
complete -c apparmor_parser -l max-jobs -d 'X Item "--max-jobs n" When --jobs is set to a scaling value (ie'
complete -c apparmor_parser -s O -l optimize -d 'X Item "-O n, --optimize=n" Set the optimization flags used by policy compila…'
complete -c apparmor_parser -l abort-on-error -d 'X Item "--abort-on-error Abort processing of profiles on the first error enco…'
complete -c apparmor_parser -l skip-bad-cache-rebuild -d 'X Item "--skip-bad-cache-rebuild The default behavior of the parser is to che…'
complete -c apparmor_parser -l estimated-compile-size -d 'X Item "--estimated-compile-size Adjust the internal parameter used to estima…'
complete -c apparmor_parser -l config-file -d 'X Item "--config-file" Specify the config file to use instead of /etc/apparmo…'
complete -c apparmor_parser -s V -l version
complete -c apparmor_parser -s h -l help
complete -c apparmor_parser -s N -l names
complete -c apparmor_parser -s p -l preprocess
complete -c apparmor_parser -s S -l stdout
complete -c apparmor_parser -s o -l ofile
complete -c apparmor_parser -l purge-cache
complete -c apparmor_parser -s a -l add
complete -c apparmor_parser -s r -l replace
complete -c apparmor_parser -s R -l remove
complete -c apparmor_parser -l print-config-file

