# apparmor_status
# Autogenerated from man page /usr/share/man/man8/apparmor_status.8.gz
complete -c apparmor_status -l enabled -d 'X Item "--enabled" returns error code if AppArmor is not enabled'
complete -c apparmor_status -l profiled -d 'X Item "--profiled" displays the number of loaded AppArmor policies'
complete -c apparmor_status -l enforced -d 'X Item "--enforced" displays the number of loaded enforcing AppArmor policies'
complete -c apparmor_status -l complaining -d 'X Item "--complaining" displays the number of loaded non-enforcing AppArmor p…'
complete -c apparmor_status -l kill -d 'X Item "--kill" displays the number of loaded enforcing AppArmor policies tha…'
complete -c apparmor_status -l prompt -d 'X Item "--prompt" displays the number of loaded enforcing AppArmor policies, …'
complete -c apparmor_status -l special-unconfined -d 'X Item "--special-unconfined" displays the number of loaded non-enforcing App…'
complete -c apparmor_status -l process-mixed -d 'X Item "--process-mixed displays the number of processes confined by profile …'
complete -c apparmor_status -l verbose -d 'X Item "--verbose" '
complete -c apparmor_status -l json -d 'X Item "--json" displays multiple data points about loaded AppArmor policy se…'
complete -c apparmor_status -l pretty-json -d 'X Item "--pretty-json" same as --json, formatted to be readable by humans as …'
complete -c apparmor_status -l show -d 'X Item "--show" what data sets to show information about'
complete -c apparmor_status -l count -d 'X Item "--count" display only counts for selected information'
complete -c apparmor_status -l 'filter.mode' -d 'X Item "--filter'
complete -c apparmor_status -l 'filter.profiles' -d 'X Item "--filter'
complete -c apparmor_status -l 'filter.pid' -d 'X Item "--filter'
complete -c apparmor_status -l 'filter.exe' -d 'X Item "--filter'
complete -c apparmor_status -l help

