# cal
# Autogenerated from man page /mnt/d/msys64/usr/share/man/man1/cal.1.gz
complete -c cal -s 1 -l one -d 'Display single month output.  (This is the default. )'
complete -c cal -s 3 -l three -d 'Display three months spanning the date'
complete -c cal -s n -l months -d 'Display number of months, starting from the month containing the date'
complete -c cal -s S -l span -d 'Display months spanning the date'
complete -c cal -s s -l sunday -d 'Display Sunday as the first day of the week'
complete -c cal -s m -l monday -d 'Display Monday as the first day of the week'
complete -c cal -l iso -d 'Display the proleptic Gregorian calendar exclusively'
complete -c cal -s j -l julian -d 'Use day-of-year numbering for all calendars'
complete -c cal -l reform -d 'This option sets the adoption date of the Gregorian calendar reform'
complete -c cal -s y -l year -d 'Display a calendar for the whole year'
complete -c cal -s Y -l twelve -d 'Display a calendar for the next twelve months'
complete -c cal -s w -l week -d 'Display week numbers in the calendar (US or ISO-8601)'
complete -c cal -l color -d 'Colorize the output'
complete -c cal -s V -l version -d 'Display version information and exit'
complete -c cal -s h -l help -d 'Display help text and exit.  PARAMETERS'

