# captoinfo
# Autogenerated from man page /usr/share/man/man1/captoinfo.1.gz
complete -c captoinfo -s I -d 'option implied.  You can use other %tic options such as'
complete -c captoinfo -s 1
complete -c captoinfo -s f
complete -c captoinfo -s v
complete -c captoinfo -s w -d and
complete -c captoinfo -s x -d 'The -V option reports the version of %ncurses associated with this program an…'

