# cloud-init
# Autogenerated from man page /usr/share/man/man1/cloud-init.1.gz
complete -c cloud-init -s h -l help -d 'Show help message and exit'
complete -c cloud-init -s v -l version -d 'Show program\'s version number and exit'
complete -c cloud-init -l all-stages -d 'INTERNAL: Run cloud-init\'s stages under a single process using a syncronizati…'
complete -c cloud-init -s d -l debug -d 'Show additional pre-action logging (default: False)'
complete -c cloud-init -l force -d 'Force running even if no datasource is found (use at your own risk)'

