# cpan5.38-x86_64-linux-gnu
# Autogenerated from man page /usr/share/man/man1/cpan5.38-x86_64-linux-gnu.1.gz
complete -c 'cpan5.38-x86_64-linux-gnu' -s a
complete -c 'cpan5.38-x86_64-linux-gnu' -s A
complete -c 'cpan5.38-x86_64-linux-gnu' -s c
complete -c 'cpan5.38-x86_64-linux-gnu' -s C
complete -c 'cpan5.38-x86_64-linux-gnu' -s D
complete -c 'cpan5.38-x86_64-linux-gnu' -s f
complete -c 'cpan5.38-x86_64-linux-gnu' -s i -d '        % cpan -f -i Module::Foo'
complete -c 'cpan5.38-x86_64-linux-gnu' -s F
complete -c 'cpan5.38-x86_64-linux-gnu' -s g
complete -c 'cpan5.38-x86_64-linux-gnu' -s G
complete -c 'cpan5.38-x86_64-linux-gnu' -s h
complete -c 'cpan5.38-x86_64-linux-gnu' -s I
complete -c 'cpan5.38-x86_64-linux-gnu' -s j
complete -c 'cpan5.38-x86_64-linux-gnu' -s J
complete -c 'cpan5.38-x86_64-linux-gnu' -s l
complete -c 'cpan5.38-x86_64-linux-gnu' -s L
complete -c 'cpan5.38-x86_64-linux-gnu' -s m
complete -c 'cpan5.38-x86_64-linux-gnu' -s M
complete -c 'cpan5.38-x86_64-linux-gnu' -s n
complete -c 'cpan5.38-x86_64-linux-gnu' -s O
complete -c 'cpan5.38-x86_64-linux-gnu' -s p
complete -c 'cpan5.38-x86_64-linux-gnu' -s P
complete -c 'cpan5.38-x86_64-linux-gnu' -s r
complete -c 'cpan5.38-x86_64-linux-gnu' -s s
complete -c 'cpan5.38-x86_64-linux-gnu' -s t
complete -c 'cpan5.38-x86_64-linux-gnu' -s T
complete -c 'cpan5.38-x86_64-linux-gnu' -s u
complete -c 'cpan5.38-x86_64-linux-gnu' -s v
complete -c 'cpan5.38-x86_64-linux-gnu' -s V
complete -c 'cpan5.38-x86_64-linux-gnu' -s w
complete -c 'cpan5.38-x86_64-linux-gnu' -s x
complete -c 'cpan5.38-x86_64-linux-gnu' -s X

