# cygcheck
# Autogenerated from man page /mnt/d/msys64/usr/share/man/man1/cygcheck.1
complete -c cygcheck -s c -d 'option checks the version and status of installed Cygwin packages'
complete -c cygcheck -s v -d option
complete -c cygcheck -s d -d 'option and cygcheck will only output the name and version for each package'
complete -c cygcheck -s n -d 'option to output only the names of packages'
complete -c cygcheck -s s -d 'option, cygcheck will give general system information'
complete -c cygcheck -s e -d 'option allows to seach for available packages in the Cygwin distribution'
complete -c cygcheck -l requires -d and
complete -c cygcheck -l build-reqs -d 'options allow to search for packages which have a certain dependency, either …'
complete -c cygcheck -s i -d 'option prints a lot of information available for installed packages, as well …'
complete -c cygcheck -l inst
complete -c cygcheck -l curr
complete -c cygcheck -l prev
complete -c cygcheck -l test
complete -c cygcheck -l deps -d and
complete -c cygcheck -l build-deps -d 'options allow to print additional dependency information'
complete -c cygcheck -l -----------------------
complete -c cygcheck -s f -d 'option helps you to track down which package a file came from, and'
complete -c cygcheck -s l -d 'lists all files in a package'
complete -c cygcheck -s h -d 'option prints additional helpful messages in the report, at the beginning of …'
complete -c cygcheck -s r -d 'option causes cygcheck to search your registry for information that is releva…'
complete -c cygcheck -s p -d 'option can be used to search the entire official Cygwin package repository'

