# cygpath
# Autogenerated from man page /mnt/d/msys64/usr/share/man/man1/cygpath.1
complete -c cygpath -s u -d and
complete -c cygpath -s w -d 'options indicate whether you want a conversion to UNIX (POSIX) format (-u) or…'
complete -c cygpath -s d -d 'to get DOS-style (8. 3) file and path names.  The'
complete -c cygpath -s m -d 'option will output Windows-style format but with forward slashes instead of b…'
complete -c cygpath -s l -d and
complete -c cygpath -s s -d 'options to use normal (long) or DOS-style (short) form.  The'
complete -c cygpath -s C -d 'option allows to specify a Windows codepage to print DOS and Windows paths cr…'
complete -c cygpath -s U -d 'option allows to use cygpath to create unambiguous Unix paths pointing outsid…'
complete -c cygpath -s p -d 'option means that you want to convert a path-style string rather than a singl…'
complete -c cygpath -s i -d 'option supresses the print out of the usage message if no filename argument w…'
complete -c cygpath -s D
complete -c cygpath -s H
complete -c cygpath -s P
complete -c cygpath -s S
complete -c cygpath -s W -d 'output directories used by Windows that are not the same on all systems, for …'
complete -c cygpath -s A -d 'option forces use of the "All Users" directories instead of the current user …'
complete -c cygpath -s O -d and
complete -c cygpath -s F -d 'outputs other special folders specified by their internal numeric code (decim…'

