# debconf
# Autogenerated from man page /usr/share/man/man1/debconf.1.gz
complete -c debconf -o opackage -l owner -d 'X Item "-opackage, --owner=package" Tell debconf what package the command it …'
complete -c debconf -o ftype -l frontend -d 'X Item "-ftype, --frontend=type" Select the frontend to use'
complete -c debconf -o pvalue -l priority -d 'X Item "-pvalue, --priority=value" Specify the minimum priority of question t…'
complete -c debconf -l terse

