# debconf-copydb
# Autogenerated from man page /usr/share/man/man1/debconf-copydb.1.gz
complete -c debconf-copydb -s p -l pattern -d 'X Item "-p pattern, --pattern pattern" If this is specified, only items in so…'
complete -c debconf-copydb -l owner-pattern -d 'X Item "--owner-pattern pattern" If this is specified, only items in sourcedb…'
complete -c debconf-copydb -s c -l config

