# debconf-apt-progress
# Autogenerated from man page /usr/share/man/man1/debconf-apt-progress.1.gz
complete -c debconf-apt-progress -l config -d 'X Item "--config" Print environment variables necessary to start up a progres…'
complete -c debconf-apt-progress -l start -d 'X Item "--start" Start up a progress bar, running from 0 to 100 by default'
complete -c debconf-apt-progress -l from -d 'X Item "--from waypoint" If used with --start, make the progress bar begin at…'
complete -c debconf-apt-progress -l to -d 'X Item "--to waypoint" If used with --start, make the progress bar end at way…'
complete -c debconf-apt-progress -l stop -d 'X Item "--stop" Stop a running progress bar'
complete -c debconf-apt-progress -l no-progress -d 'X Item "--no-progress" Avoid starting, stopping, or stepping the progress bar'
complete -c debconf-apt-progress -l dlwaypoint -d 'X Item "--dlwaypoint percentage" Specify what percent of the progress bar to …'
complete -c debconf-apt-progress -l logfile -d 'X Item "--logfile file" Send the normal output from apt to the given file'
complete -c debconf-apt-progress -l logstderr -d 'X Item "--logstderr" Send the normal output from apt to stderr'

