# debconf-show
# Autogenerated from man page /usr/share/man/man1/debconf-show.1.gz
complete -c debconf-show -l db -d 'X Item "--db=dbname" Specify the database to query'
complete -c debconf-show -l listowners -d 'X Item "--listowners" Lists all owners of questions in the database'
complete -c debconf-show -l listdbs

