# debconf-set-selections
# Autogenerated from man page /usr/share/man/man1/debconf-set-selections.1.gz
complete -c debconf-set-selections -l verbose -s v -d 'X Item "--verbose, -v" verbose output'
complete -c debconf-set-selections -l checkonly -s c

