# do-release-upgrade
# Autogenerated from man page /usr/share/man/man8/do-release-upgrade.8.gz
complete -c do-release-upgrade -s h -l help -d 'show this help message and exit'
complete -c do-release-upgrade -s V -l version -d 'Show version and exit'
complete -c do-release-upgrade -s d -l devel-release -d 'If using the latest supported release, upgrade to the development release'
complete -c do-release-upgrade -l data-dir -d 'Directory that contains the data files'
complete -c do-release-upgrade -s p -l proposed -d 'Try upgrading to the latest release using the upgrader from Ubuntu-proposed'
complete -c do-release-upgrade -s m -l mode -d 'Run in a special upgrade mode'
complete -c do-release-upgrade -s f -l frontend -d 'Run the specified frontend'
complete -c do-release-upgrade -s c -l check-dist-upgrade-only -d 'Check only if a new distribution release is available and report the result v…'
complete -c do-release-upgrade -l allow-third-party -d 'Try the upgrade with third party mirrors and repositories enabled instead of …'

