# dpkg-preconfigure
# Autogenerated from man page /usr/share/man/man8/dpkg-preconfigure.8.gz
complete -c dpkg-preconfigure -o ftype -l frontend -d 'X Item "-ftype, --frontend=type" Select the frontend to use'
complete -c dpkg-preconfigure -o pvalue -l priority -d 'X Item "-pvalue, --priority=value" Set the lowest priority of questions you a…'
complete -c dpkg-preconfigure -l terse -d 'X Item "--terse" Enables terse output mode.  This affects only some frontends'
complete -c dpkg-preconfigure -l apt -d 'X Item "--apt" Run in apt mode'
complete -c dpkg-preconfigure -s h -l help

