# dpkg-architecture
# Autogenerated from man page /usr/share/man/man1/dpkg-architecture.1.gz
complete -c dpkg-architecture -s a -l host-arch -d 'X Item "-a, --host-arch architecture" Set the host Debian architecture'
complete -c dpkg-architecture -s t -l host-type -d 'X Item "-t, --host-type gnu-system-type" Set the host GNU system type'
complete -c dpkg-architecture -s A -l target-arch -d 'X Item "-A, --target-arch architecture" Set the target Debian architecture (s…'
complete -c dpkg-architecture -s T -l target-type -d 'X Item "-T, --target-type gnu-system-type" Set the target GNU system type (si…'
complete -c dpkg-architecture -s W -l match-wildcard -d 'X Item "-W, --match-wildcard architecture-wildcard" Restrict the architecture…'
complete -c dpkg-architecture -s B -l match-bits -d 'X Item "-B, --match-bits architecture-bits" Restrict the architectures listed…'
complete -c dpkg-architecture -s E -l match-endian -d 'X Item "-E, --match-endian architecture-endianness" Restrict the architecture…'
complete -c dpkg-architecture -l print-format -d 'X Item "--print-format format" Sets the output format for --print-set and --p…'
complete -c dpkg-architecture -s l -l list
complete -c dpkg-architecture -s e -l equal
complete -c dpkg-architecture -s i -l is
complete -c dpkg-architecture -s q -l query
complete -c dpkg-architecture -s s -l print-set
complete -c dpkg-architecture -s u -l print-unset
complete -c dpkg-architecture -s c -l command
complete -c dpkg-architecture -s L -l list-known
complete -c dpkg-architecture -s '?' -l help
complete -c dpkg-architecture -l version
complete -c dpkg-architecture -s f -l force

