# dpkg-distaddfile
# Autogenerated from man page /usr/share/man/man1/dpkg-distaddfile.1.gz
complete -c dpkg-distaddfile -o ffiles-list-file -d 'X Item "-ffiles-list-file" Read or write the list of files to be uploaded her…'
complete -c dpkg-distaddfile -s '?' -l help -d 'X Item "-?, --help" Show the usage message and exit'
complete -c dpkg-distaddfile -l version

