# dpkg-vendor
# Autogenerated from man page /usr/share/man/man1/dpkg-vendor.1.gz
complete -c dpkg-vendor -l is
complete -c dpkg-vendor -l derives-from
complete -c dpkg-vendor -l query
complete -c dpkg-vendor -l help
complete -c dpkg-vendor -l version
complete -c dpkg-vendor -l vendor

