# dpkg-parsechangelog
# Autogenerated from man page /usr/share/man/man1/dpkg-parsechangelog.1.gz
complete -c dpkg-parsechangelog -s l -l file -d 'X Item "-l, --file changelog-file" Specifies the changelog file to read infor…'
complete -c dpkg-parsechangelog -s F -d 'X Item "-F changelog-format" Specifies the format of the changelog'
complete -c dpkg-parsechangelog -s L -d 'X Item "-L libdir" Obsolete option without effect (since dpkg 1. 18. 8)'
complete -c dpkg-parsechangelog -s S -l show-field -d 'X Item "-S, --show-field field" Specifies the name of the field to show (sinc…'
complete -c dpkg-parsechangelog -s '?' -l help -d 'X Item "-?, --help" Show the usage message and exit'
complete -c dpkg-parsechangelog -l version -d 'X Item "--version" Show the version and exit'
complete -c dpkg-parsechangelog -l format -d 'X Item "--format output-format" Set the output format'
complete -c dpkg-parsechangelog -l reverse -d 'X Item "--reverse" Include all changes in reverse order (since dpkg 1. 19. 1)'
complete -c dpkg-parsechangelog -l all -d 'X Item "--all" Include all changes'
complete -c dpkg-parsechangelog -s s -l since -d 'X Item "-s, --since version"'
complete -c dpkg-parsechangelog -s v -d 'X Item "-v version" . PD Include all changes later than version'
complete -c dpkg-parsechangelog -s u -l until -d 'X Item "-u, --until version" Include all changes earlier than version'
complete -c dpkg-parsechangelog -s f -l from -d 'X Item "-f, --from version" Include all changes equal or later than version'
complete -c dpkg-parsechangelog -s t -l to -d 'X Item "-t, --to version" Include all changes up to or equal than version'
complete -c dpkg-parsechangelog -s c -l count -d 'X Item "-c, --count number"'
complete -c dpkg-parsechangelog -s n -d 'X Item "-n number" '
complete -c dpkg-parsechangelog -s o -l offset

