# dpkg-gensymbols
# Autogenerated from man page /usr/share/man/man1/dpkg-gensymbols.1.gz
complete -c dpkg-gensymbols -o Ppackage-build-dir -d 'X Item "-Ppackage-build-dir" Scan package-build-dir instead of debian/tmp'
complete -c dpkg-gensymbols -o ppackage -d 'X Item "-ppackage" Define the package name'
complete -c dpkg-gensymbols -o vversion -d 'X Item "-vversion" Define the package version'
complete -c dpkg-gensymbols -o elibrary-file -d 'X Item "-elibrary-file" Only analyze libraries explicitly listed instead of f…'
complete -c dpkg-gensymbols -o ldirectory -d 'X Item "-ldirectory" Prepend directory to the list of directories to search f…'
complete -c dpkg-gensymbols -o Ifilename -d 'X Item "-Ifilename" Use filename as reference file to generate the symbols fi…'
complete -c dpkg-gensymbols -s O -d 'X Item "-O[filename]" Print the generated symbols file to standard output or …'
complete -c dpkg-gensymbols -s t -d 'X Item "-t" Write the symbol file in template mode rather than the format com…'
complete -c dpkg-gensymbols -s c -d 'X Item "-c[0-4]" Define the checks to do when comparing the generated symbols…'
complete -c dpkg-gensymbols -s q -d 'X Item "-q" Keep quiet and never generate a diff between generated symbols fi…'
complete -c dpkg-gensymbols -o aarch -d 'X Item "-aarch" Assume arch as host architecture when processing symbol files'
complete -c dpkg-gensymbols -s d -d 'X Item "-d" Enable debug mode'
complete -c dpkg-gensymbols -s V -d 'X Item "-V" Enable verbose mode'
complete -c dpkg-gensymbols -s '?' -l help -d 'X Item "-?, --help" Show the usage message and exit'
complete -c dpkg-gensymbols -s P -d 'was used)'
complete -c dpkg-gensymbols -l version

