# dpkg-scansources
# Autogenerated from man page /usr/share/man/man1/dpkg-scansources.1.gz
complete -c dpkg-scansources -s n -l no-sort -d 'X Item "-n, --no-sort" Do not sort the index stanzas'
complete -c dpkg-scansources -s e -l extra-override -d 'X Item "-e, --extra-override file" Scan file to find supplementary overrides …'
complete -c dpkg-scansources -s s -l source-override -d 'X Item "-s, --source-override file" Use file as the source override file (the…'
complete -c dpkg-scansources -l debug -d 'X Item "--debug" Turn debugging on'
complete -c dpkg-scansources -l help -d 'X Item "--help" Show the usage message and exit'
complete -c dpkg-scansources -l version

