# dpkg-genbuildinfo
# Autogenerated from man page /usr/share/man/man1/dpkg-genbuildinfo.1.gz
complete -c dpkg-genbuildinfo -l build -d 'X Item "--build=type" Specifies the build type from a comma-separated list of…'
complete -c dpkg-genbuildinfo -o ccontrolfile -d 'X Item "-ccontrolfile" Specifies the main source control file to read informa…'
complete -c dpkg-genbuildinfo -o lchangelog-file -d 'X Item "-lchangelog-file" Specifies the changelog file to read information fr…'
complete -c dpkg-genbuildinfo -o ffiles-list-file -d 'X Item "-ffiles-list-file" Specifies where is the list of files that have bee…'
complete -c dpkg-genbuildinfo -o Fchangelog-format -d 'X Item "-Fchangelog-format" Specifies the format of the changelog'
complete -c dpkg-genbuildinfo -s O -d 'X Item "-O[filename]" Print the buildinfo file to standard output (or filenam…'
complete -c dpkg-genbuildinfo -o uupload-files-dir -d 'X Item "-uupload-files-dir" Look for the files to be uploaded in upload-files…'
complete -c dpkg-genbuildinfo -l always-include-kernel -d 'X Item "--always-include-kernel" By default, the Build-Kernel-Version field w…'
complete -c dpkg-genbuildinfo -l always-include-path -d 'X Item "--always-include-path" By default, the Build-Path field will only be …'
complete -c dpkg-genbuildinfo -l admindir -d 'X Item "--admindir=dir" Change the location of the dpkg database'
complete -c dpkg-genbuildinfo -s q -d 'X Item "-q" dpkg-genbuildinfo might produce informative messages on standard …'
complete -c dpkg-genbuildinfo -s '?' -l help -d 'X Item "-?, --help" Show the usage message and exit'
complete -c dpkg-genbuildinfo -l version

