# dpkg-reconfigure
# Autogenerated from man page /usr/share/man/man8/dpkg-reconfigure.8.gz
complete -c dpkg-reconfigure -o ftype -l frontend -d 'X Item "-ftype, --frontend=type" Select the frontend to use'
complete -c dpkg-reconfigure -o pvalue -l priority -d 'X Item "-pvalue, --priority=value" Specify the minimum priority of question t…'
complete -c dpkg-reconfigure -l terse -d 'X Item "--terse" Enables terse output mode.  This affects only some frontends'
complete -c dpkg-reconfigure -l default-priority -d 'X Item "--default-priority" Use whatever the default priority of question is,…'
complete -c dpkg-reconfigure -s u -l unseen-only -d 'X Item "-u, --unseen-only" By default, all questions are shown, even if they …'
complete -c dpkg-reconfigure -l force -d 'X Item "--force" Force dpkg-reconfigure to reconfigure a package even if the …'
complete -c dpkg-reconfigure -l no-reload -d 'X Item "--no-reload" Prevent dpkg-reconfigure from reloading templates'
complete -c dpkg-reconfigure -s h -l help

