# dpkg-checkbuilddeps
# Autogenerated from man page /usr/share/man/man1/dpkg-checkbuilddeps.1.gz
complete -c dpkg-checkbuilddeps -l admindir -d 'X Item "--admindir=dir" Change the location of the dpkg database (since dpkg 1'
complete -c dpkg-checkbuilddeps -s A -d 'X Item "-A" Ignore Build-Depends-Arch and Build-Conflicts-Arch lines (since d…'
complete -c dpkg-checkbuilddeps -s B -d 'X Item "-B" Ignore Build-Depends-Indep and Build-Conflicts-Indep lines'
complete -c dpkg-checkbuilddeps -s I -d 'X Item "-I" Ignore built-in build depends and conflicts (since dpkg 1. 18. 2)'
complete -c dpkg-checkbuilddeps -s d -d 'X Item "-d build-depends-string"'
complete -c dpkg-checkbuilddeps -s c -d 'X Item "-c build-conflicts-string" '
complete -c dpkg-checkbuilddeps -s a -d 'X Item "-a arch" Check build dependencies/conflicts assuming that the package…'
complete -c dpkg-checkbuilddeps -s P -d 'X Item "-P profile[,'
complete -c dpkg-checkbuilddeps -s '?' -l help -d 'X Item "-?, --help" Show the usage message and exit'
complete -c dpkg-checkbuilddeps -l version

