# dpkg-source
# Autogenerated from man page /usr/share/man/man1/dpkg-source.1.gz
complete -c dpkg-source -o ccontrol-file -d 'X Item "-ccontrol-file" Specifies the main source control file to read inform…'
complete -c dpkg-source -o lchangelog-file -d 'X Item "-lchangelog-file" Specifies the changelog file to read information fr…'
complete -c dpkg-source -o Fchangelog-format -d 'X Item "-Fchangelog-format" Specifies the format of the changelog'
complete -c dpkg-source -l format -d 'X Item "--format=value" Use the given format for building the source package …'
complete -c dpkg-source -o Vname -d 'X Item "-Vname=value" Set an output substitution variable'
complete -c dpkg-source -o Tsubstvars-file -d 'X Item "-Tsubstvars-file" Read substitution variables in substvars-file; the …'
complete -c dpkg-source -o Dfield -d 'X Item "-Dfield=value" Override or add an output control file field'
complete -c dpkg-source -o Ufield -d 'X Item "-Ufield" Remove an output control file field'
complete -c dpkg-source -o Zcompression -l compression -d 'X Item "-Zcompression, --compression=compression" Specify the compression to …'
complete -c dpkg-source -o zlevel -l compression-level -d 'X Item "-zlevel, --compression-level=level" Compression level to use (--compr…'
complete -c dpkg-source -s i -l diff-ignore -d 'X Item "-i[regex], --diff-ignore[=regex]" You may specify a perl regular expr…'
complete -c dpkg-source -l extend-diff-ignore -d 'X Item "--extend-diff-ignore=regex" The perl regular expression specified wil…'
complete -c dpkg-source -s I -l tar-ignore -d 'X Item "-I[file-pattern], --tar-ignore[=file-pattern]" If this option is spec…'
complete -c dpkg-source -l no-copy -d 'X Item "--no-copy" Do not copy original tarballs near the extracted source pa…'
complete -c dpkg-source -l no-check -d 'X Item "--no-check" Do not check signatures and checksums before unpacking (s…'
complete -c dpkg-source -l no-overwrite-dir -d 'X Item "--no-overwrite-dir" Do not overwrite the extraction directory if it a…'
complete -c dpkg-source -l require-valid-signature -d 'X Item "--require-valid-signature" Refuse to unpack the source package if it …'
complete -c dpkg-source -l require-strong-checksums -d 'X Item "--require-strong-checksums" Refuse to unpack the source package if it…'
complete -c dpkg-source -l ignore-bad-version -d 'X Item "--ignore-bad-version" Turns the bad source package version check into…'
complete -c dpkg-source -l threads-max -d 'X Item "--threads-max=threads" Sets the maximum number of threads allowed for…'
complete -c dpkg-source -s x -l extract
complete -c dpkg-source -s b -l build
complete -c dpkg-source -l print-format
complete -c dpkg-source -l before-build
complete -c dpkg-source -l after-build
complete -c dpkg-source -l commit
complete -c dpkg-source -s '?' -l help
complete -c dpkg-source -l version
complete -c dpkg-source -l exclude -d 'option when it is called to generate a . orig. tar or '
complete -c dpkg-source -s q
complete -c dpkg-source -o sa -o sp -o sk -o su -o sr -d 'will not overwrite existing tarfiles or directories.  If this is desired then'
complete -c dpkg-source -o sA -o sP -o sK -o sU -o sR -d 'should be used instead'
complete -c dpkg-source -o ss
complete -c dpkg-source -o sn
complete -c dpkg-source -l abort-on-upstream-changes
complete -c dpkg-source -o sX -d 'options are mutually exclusive'
complete -c dpkg-source -l skip-debianization
complete -c dpkg-source -l include-binaries
complete -c dpkg-source -l single-debian-patch -l auto-commit -d 'has been used, in which case the diff is stored in the automatic patch'
complete -c dpkg-source -l no-preparation -d behavior
complete -c dpkg-source -l allow-version-of-quilt-db
complete -c dpkg-source -l include-removal
complete -c dpkg-source -l include-timestamp
complete -c dpkg-source -l create-empty-orig
complete -c dpkg-source -l no-unapply-patches -l unapply-patches
complete -c dpkg-source -l skip-patches
complete -c dpkg-source -l target-format
complete -c dpkg-source -l git-ref
complete -c dpkg-source -l git-depth

