# dpkg-gencontrol
# Autogenerated from man page /usr/share/man/man1/dpkg-gencontrol.1.gz
complete -c dpkg-gencontrol -o vversion -d 'X Item "-vversion" Sets the version number of the binary package which will b…'
complete -c dpkg-gencontrol -o Vname -d 'X Item "-Vname=value" Set an output substitution variable'
complete -c dpkg-gencontrol -o Tsubstvars-file -d 'X Item "-Tsubstvars-file" Read substitution variables in substvars-file; the …'
complete -c dpkg-gencontrol -o Dfield -d 'X Item "-Dfield=value" Override or add an output control file field'
complete -c dpkg-gencontrol -o Ufield -d 'X Item "-Ufield" Remove an output control file field'
complete -c dpkg-gencontrol -o ccontrol-file -d 'X Item "-ccontrol-file" Specifies the main source control file to read inform…'
complete -c dpkg-gencontrol -o lchangelog-file -d 'X Item "-lchangelog-file" Specifies the changelog file to read information fr…'
complete -c dpkg-gencontrol -o ffiles-list-file -d 'X Item "-ffiles-list-file" Read or write the list of files to be uploaded her…'
complete -c dpkg-gencontrol -o Fchangelog-format -d 'X Item "-Fchangelog-format" Specifies the format of the changelog'
complete -c dpkg-gencontrol -o ppackage -d 'X Item "-ppackage" Generate information for the binary package package'
complete -c dpkg-gencontrol -o nfilename -d 'X Item "-nfilename" Assume the filename of the package will be filename inste…'
complete -c dpkg-gencontrol -o is -o ip -o isp -d 'X Item "-is, -ip, -isp" These options are ignored for compatibility with olde…'
complete -c dpkg-gencontrol -o Ppackage-build-dir -d 'X Item "-Ppackage-build-dir" Scan package-build-dir instead of debian/tmp'
complete -c dpkg-gencontrol -s O -d 'X Item "-O[filename]" Print the control file to standard output (or filename …'
complete -c dpkg-gencontrol -s '?' -l help -d 'X Item "-?, --help" Show the usage message and exit'
complete -c dpkg-gencontrol -s U -d 'option to delete the fields from the control file'
complete -c dpkg-gencontrol -s P -d 'was used)'
complete -c dpkg-gencontrol -l version

