# dpkg-shlibdeps
# Autogenerated from man page /usr/share/man/man1/dpkg-shlibdeps.1.gz
complete -c dpkg-shlibdeps -o eexecutable -d 'X Item "-eexecutable" Include dependencies appropriate for the shared librari…'
complete -c dpkg-shlibdeps -o ldirectory -d 'X Item "-ldirectory" Prepend directory to the list of directories to search f…'
complete -c dpkg-shlibdeps -o ddependency-field -d 'X Item "-ddependency-field" Add dependencies to be added to the control file …'
complete -c dpkg-shlibdeps -o pvarname-prefix -d 'X Item "-pvarname-prefix" Start substitution variables with varname-prefix: i…'
complete -c dpkg-shlibdeps -s O -d 'X Item "-O[filename]" Print substitution variable settings to standard output…'
complete -c dpkg-shlibdeps -o ttype -d 'X Item "-ttype" Prefer shared library dependency information tagged for the g…'
complete -c dpkg-shlibdeps -o Llocal-shlibs-file -d 'X Item "-Llocal-shlibs-file" Read overriding shared library dependency inform…'
complete -c dpkg-shlibdeps -o Tsubstvars-file -d 'X Item "-Tsubstvars-file" Write substitution variables in substvars-file; the…'
complete -c dpkg-shlibdeps -s v -d 'X Item "-v" Enable verbose mode (since dpkg 1. 14. 8)'
complete -c dpkg-shlibdeps -o xpackage -d 'X Item "-xpackage" Exclude the package from the generated dependencies (since…'
complete -c dpkg-shlibdeps -o Spackage-build-dir -d 'X Item "-Spackage-build-dir" Look into package-build-dir first when trying to…'
complete -c dpkg-shlibdeps -o Ipackage-build-dir -d 'X Item "-Ipackage-build-dir" Ignore package-build-dir when looking for shlibs…'
complete -c dpkg-shlibdeps -l ignore-missing-info -d 'X Item "--ignore-missing-info" Do not fail if dependency information can\'t be…'
complete -c dpkg-shlibdeps -l warnings -d 'X Item "--warnings=value" value is a bit field defining the set of warnings t…'
complete -c dpkg-shlibdeps -l admindir -d 'X Item "--admindir=dir" Change the location of the dpkg database (since dpkg 1'
complete -c dpkg-shlibdeps -s '?' -l help -d 'X Item "-?, --help" Show the usage message and exit'
complete -c dpkg-shlibdeps -l version
complete -c dpkg-shlibdeps -o llibrary -d 'binary contains an unresolvable reference to symbol sym: it\'s probably a plug…'

