# dpkg-name
# Autogenerated from man page /usr/share/man/man1/dpkg-name.1.gz
complete -c dpkg-name -s a -l no-architecture -d 'X Item "-a, --no-architecture" The destination filename will not have the arc…'
complete -c dpkg-name -s k -l symlink -d 'X Item "-k, --symlink" Create a symlink, instead of moving'
complete -c dpkg-name -s o -l overwrite -d 'X Item "-o, --overwrite" Existing files will be overwritten if they have the …'
complete -c dpkg-name -s s -l subdir -d 'X Item "-s, --subdir [dir]" Files will be moved into a subdirectory'
complete -c dpkg-name -s c -l create-dir -d 'X Item "-c, --create-dir" This option can used together with the -s option'
complete -c dpkg-name -s '?' -l help -d 'X Item "-?, --help" Show the usage message and exit'
complete -c dpkg-name -s v -l version

