# dpkg-mergechangelogs
# Autogenerated from man page /usr/share/man/man1/dpkg-mergechangelogs.1.gz
complete -c dpkg-mergechangelogs -l merge-unreleased -d 'X Item "--merge-unreleased" Ignore the version number when the entries are ma…'
complete -c dpkg-mergechangelogs -s m -l merge-prereleases -d 'X Item "-m, --merge-prereleases" Drop the part after the last tilde in the ve…'
complete -c dpkg-mergechangelogs -l help -d 'X Item "--help" Show the usage message and exit'
complete -c dpkg-mergechangelogs -l version

