# dpkg-scanpackages
# Autogenerated from man page /usr/share/man/man1/dpkg-scanpackages.1.gz
complete -c dpkg-scanpackages -s t -l type -d 'X Item "-t, --type type" Scan for *. type packages, instead of *. deb'
complete -c dpkg-scanpackages -s e -l extra-override -d 'X Item "-e, --extra-override file" Scan file to find supplementary overrides …'
complete -c dpkg-scanpackages -s a -l arch -d 'X Item "-a, --arch arch" Use a pattern consisting of *_all. deb and *_arch'
complete -c dpkg-scanpackages -s h -l hash -d 'X Item "-h, --hash hash-list" Only generate file hashes for the comma-specifi…'
complete -c dpkg-scanpackages -s m -l multiversion -d 'X Item "-m, --multiversion" Include all found packages in the output'
complete -c dpkg-scanpackages -s M -l medium -d 'X Item "-M, --medium id-string" Add an X-Medium field containing the value id…'
complete -c dpkg-scanpackages -s '?' -l help -d 'X Item "-?, --help" Show the usage message and exit'
complete -c dpkg-scanpackages -l version

