# dpkg-buildapi
# Autogenerated from man page /usr/share/man/man1/dpkg-buildapi.1.gz
complete -c dpkg-buildapi -l help
complete -c dpkg-buildapi -l version
complete -c dpkg-buildapi -o ccontrol-file

