# dpkg-buildflags
# Autogenerated from man page /usr/share/man/man1/dpkg-buildflags.1.gz
complete -c dpkg-buildflags -l dump
complete -c dpkg-buildflags -l list
complete -c dpkg-buildflags -l status
complete -c dpkg-buildflags -l export
complete -c dpkg-buildflags -l get
complete -c dpkg-buildflags -l origin
complete -c dpkg-buildflags -l query
complete -c dpkg-buildflags -l query-features
complete -c dpkg-buildflags -l help
complete -c dpkg-buildflags -l version
complete -c dpkg-buildflags -o Wl -d 'and , have to be stripped from these options).  Default value: empty'
complete -c dpkg-buildflags -o D_LARGEFILE_SOURCE -o D_FILE_OFFSET_BITS
complete -c dpkg-buildflags -o U_LARGEFILE_SOURCE -o U_FILE_OFFSET_BITS -o U_TIME_BITS -d future
complete -c dpkg-buildflags -o Werror -d 'bug 4'
complete -c dpkg-buildflags -o fsanitize -d 'LDFLAGS and -fsanitize=address -fno-omit-frame-pointer to CFLAGS and CXXFLAGS'
complete -c dpkg-buildflags -o Wformat -d 'to CFLAGS, CXXFLAGS, OBJCFLAGS and OBJCXXFLAGS'
complete -c dpkg-buildflags -o D_FORTIFY_SOURCE -d 'to CPPFLAGS'
complete -c dpkg-buildflags -o nostdlib -o ffreestanding -d 'stackprotectorstrong 4'
complete -c dpkg-buildflags -o fstack-protector-strong -d 'to CFLAGS, CXXFLAGS, OBJCFLAGS, OBJCXXFLAGS, FFLAGS and FCFLAGS'
complete -c dpkg-buildflags -o fstack-clash-protection -d 'CFLAGS, CXXFLAGS, OBJCFLAGS, OBJCXXFLAGS, FFLAGS and FCFLAGS'
complete -c dpkg-buildflags -s z -d 'to LDFLAGS'
complete -c dpkg-buildflags -o fPIE -d 'CXXFLAGS, OBJCFLAGS, OBJCXXFLAGS, FFLAGS and FCFLAGS, and'
complete -c dpkg-buildflags -o pie -d 'When the setting is disabled and gcc injects the flags, it adds'
complete -c dpkg-buildflags -o fno-PIE -d 'CXXFLAGS, OBJCFLAGS, OBJCXXFLAGS, FFLAGS and FCFLAGS, and'
complete -c dpkg-buildflags -o no-pie -d LDFLAGS
complete -c dpkg-buildflags -o fPIC
complete -c dpkg-buildflags -o Wdate-time -d 'to CPPFLAGS'
complete -c dpkg-buildflags -o ffile-prefix-map -d 'to CFLAGS, CXXFLAGS, OBJCFLAGS, OBJCXXFLAGS, FFLAGS and FCFLAGS where BUILDPA…'
complete -c dpkg-buildflags -o fdebug-prefix-map -d 'to CFLAGS, CXXFLAGS, OBJCFLAGS, OBJCXXFLAGS, FFLAGS and FCFLAGS where BUILDPA…'

