# dumper
# Autogenerated from man page /mnt/d/msys64/usr/share/man/man1/dumper.1
complete -c dumper -s n -l nokill
complete -c dumper -s d -l verbose
complete -c dumper -s h -l help
complete -c dumper -s q -l quiet
complete -c dumper -s V -l version -d DESCRIPTION

