# getconf
# Autogenerated from man page /mnt/d/msys64/usr/share/man/man1/getconf.1
complete -c getconf -s v -d 'option, the parameter denotes a specification for which the value of the conf…'
complete -c getconf -s a -d 'option to print a list of all available configuration variables for the syste…'

