# gkill
# Autogenerated from man page /mnt/d/msys64/usr/share/man/man1/gkill.1.gz
complete -c gkill -s l -l list -d 'list signal names, or convert signal names to/from numbers'
complete -c gkill -s t -l table -d 'print a table of signal information'
complete -c gkill -l help -d 'display this help and exit'
complete -c gkill -s s -l signal -o SIGNAL -d 'specify the name or number of the signal to be sent'
complete -c gkill -l version -d 'output version information and exit'

