# gpg-mail-tube
# Autogenerated from man page /mnt/d/msys64/usr/share/man/man1/gpg-mail-tube.1.gz
complete -c gpg-mail-tube -l verbose -d 'TQ   -v Enable extra informational output'
complete -c gpg-mail-tube -l quiet -d 'TQ   -q Try to be as quiet as possible'
complete -c gpg-mail-tube -l log-file -d 'Write log output to file.   Use \'socket://\' to log to a socket'
complete -c gpg-mail-tube -l no-stderr -d 'Suppresses all output to stderr'
complete -c gpg-mail-tube -l header -d 'Add the mail header "name: value" to the output'
complete -c gpg-mail-tube -l setenv -d 'Put the given environment string into the environment of this process and of …'
complete -c gpg-mail-tube -l as-attach -d 'TQ   -a Do not write a PGP/MIME mail but emit a simple body along with an att…'
complete -c gpg-mail-tube -l gpg -d 'Use the specified command gpgcmd instead of gpg'
complete -c gpg-mail-tube -l vsd -d 'Use the gpg from a GnuPG VS-DesktopÂ® AppImage'
complete -c gpg-mail-tube -l version -d 'Print version of the program and exit'
complete -c gpg-mail-tube -s v -d 'Enable extra informational output'
complete -c gpg-mail-tube -s q -d 'Try to be as quiet as possible'
complete -c gpg-mail-tube -s a -d 'Do not write a PGP/MIME mail but emit a simple body along with an attachment …'
complete -c gpg-mail-tube -l help -d 'Display a brief help page and exit'

