# halt
# Autogenerated from man page /usr/share/man/man8/halt.8.gz
complete -c halt -l help
complete -c halt -l halt
complete -c halt -s p -l poweroff
complete -c halt -l reboot
complete -c halt -s f -l force
complete -c halt -s w -l wtmp-only
complete -c halt -s d -l no-wtmp
complete -c halt -s n -l no-sync
complete -c halt -l no-wall

