# infotocap
# Autogenerated from man page /usr/share/man/man1/infotocap.1.gz
complete -c infotocap -s C -d 'option implied.  You can use other %tic options such as'
complete -c infotocap -s 1
complete -c infotocap -s f
complete -c infotocap -s v
complete -c infotocap -s w -d and
complete -c infotocap -s x -d 'The -V option reports the version of %ncurses associated with this program an…'

