# keyboxd
# Autogenerated from man page /usr/share/man/man1/keyboxd.1.gz
complete -c keyboxd -l options -d 'Reads configuration from file instead of from the default per-user configurat…'
complete -c keyboxd -l homedir -d 'Set the name of the home directory to dir'
complete -c keyboxd -l verbose -d 'Outputs additional information while running'
complete -c keyboxd -l log-file -d 'Append all logging output to file'
complete -c keyboxd -l debug-level -d 'Select the debug level for investigating problems'
complete -c keyboxd -l debug -d 'Set debugging flags'
complete -c keyboxd -l version -d 'Print  the program version and licensing information'
complete -c keyboxd -l help -d 'Print a usage message summarizing the most useful command-line options'
complete -c keyboxd -l server -d 'Run in server mode and wait for commands on the stdin'
complete -c keyboxd -l daemon -d 'Run in background daemon mode and listen for commands on a socket'
complete -c keyboxd -l supervised -d 'Run in the foreground, sending logs to stderr, and listening on file descript…'
complete -c keyboxd -s v
complete -c keyboxd -l debug-all -d 'Same as --debug=0xffffffff'

