# landscape-sysinfo
# Autogenerated from man page /usr/share/man/man1/landscape-sysinfo.1.gz
complete -c landscape-sysinfo -l version -d 'show program\'s version number and exit'
complete -c landscape-sysinfo -s h -l help -d 'show this help message and exit'
complete -c landscape-sysinfo -s c -l config -d 'Use config from this file (any command line options override settings from th…'
complete -c landscape-sysinfo -s d -l data-path -d 'The directory to store data files in (default: \'/var/lib/landscape/client/\')'
complete -c landscape-sysinfo -l sysinfo-plugins -d 'Comma-delimited list of sysinfo plugins to use'
complete -c landscape-sysinfo -l exclude-sysinfo-plugins -d 'Comma-delimited list of sysinfo plugins to NOT use'

