# landscape-client
# Autogenerated from man page /usr/share/man/man1/landscape-client.1.gz
complete -c landscape-client -l version -d 'Show program\'s version number and exit'
complete -c landscape-client -s h -l help -d 'Show this help message and exit'
complete -c landscape-client -s c -l config -d 'Use config from this file (any command line options override settings from th…'
complete -c landscape-client -s d -l data-path -d 'The directory to store data files in (default: \'/var/lib/landscape/client/\')'
complete -c landscape-client -s q -l quiet -d 'Do not log to the standard output'
complete -c landscape-client -s l -l log-dir -d 'The directory to write log files to (default: \'/var/log/landscape\')'
complete -c landscape-client -l log-level -d 'One of debug, info, warning, error or critical'
complete -c landscape-client -s u -l url -d 'The server URL to connect to'
complete -c landscape-client -l ping-url -d 'The URL to perform lightweight exchange initiation with'
complete -c landscape-client -s k -l ssl-public-key -d 'The public SSL key to verify the server'
complete -c landscape-client -l ignore-sigint -d 'Ignore interrupt signals'
complete -c landscape-client -l ignore-sigusr1 -d 'Ignore SIGUSR1 signal to rotate logs'
complete -c landscape-client -l daemon -d 'Fork and run in the background'
complete -c landscape-client -l pid-file -d 'The file to write the PID to'
complete -c landscape-client -l monitor-only -d 'Don\'t enable management features'

