# lsb_release
# Autogenerated from man page /usr/share/man/man1/lsb_release.1.gz
complete -c lsb_release -s h -l help -d 'Show a help message with a list of options and exit'
complete -c lsb_release -s v -l version -d 'Show \\s-1LSB\\s0 modules this system supports'
complete -c lsb_release -s i -l id -d 'Show distributor \\s-1ID. \\s0'
complete -c lsb_release -s d -l description -d 'Show description of this distribution'
complete -c lsb_release -s r -l release -d 'Show release number of this distribution'
complete -c lsb_release -s c -l codename -d 'Show code name of this distribution'
complete -c lsb_release -s a -l all -d 'Show all of the above information'

