# lto-dump-13
# Autogenerated from man page /usr/share/man/man1/lto-dump-13.1.gz
complete -c lto-dump-13 -o list -d 'Dumps list of details of functions and variables'
complete -c lto-dump-13 -o demangle -d 'Dump the demangled output'
complete -c lto-dump-13 -o defined-only -d 'Dump only the defined symbols'
complete -c lto-dump-13 -o print-value -d 'Dump initial values of the variables'
complete -c lto-dump-13 -o name-sort -d 'Sort the symbols alphabetically'
complete -c lto-dump-13 -o size-sort -d 'Sort the symbols according to size'
complete -c lto-dump-13 -o reverse-sort -d 'Dump the symbols in reverse order'
complete -c lto-dump-13 -o no-sort -d 'Dump the symbols in order of occurrence'
complete -c lto-dump-13 -o symbol -d 'Dump the details of specific symbol'
complete -c lto-dump-13 -o objects -d 'Dump the details of \\s-1LTO\\s0 objects'
complete -c lto-dump-13 -o type-stats -d 'Dump the statistics of tree types'
complete -c lto-dump-13 -o tree-stats -d 'Dump the statistics of trees'
complete -c lto-dump-13 -o gimple-stats -d 'Dump the statistics of gimple statements'
complete -c lto-dump-13 -o dump-level -d 'For deciding the optimization level of body'
complete -c lto-dump-13 -o dump-body -d 'Dump the specific gimple body'

