# mawk
# Autogenerated from man page /usr/share/man/man1/mawk.1.gz
complete -c mawk -s f -d 'Program text is read from file instead of from the command line'
complete -c mawk -s v -d 'assigns  value to program variable R var '
complete -c mawk -s '\\' -d 'indicates the unambiguous end of options'
complete -c mawk -s W -d 'writes an assembler like listing of the internal representation of the progra…'
complete -c mawk -s F -d 'sets the field separator, FS, to value '
complete -c mawk -l version
complete -c mawk -o Wversion
complete -c mawk -l help
complete -c mawk -l posix
complete -c mawk -s r
complete -c mawk -l re-interval
complete -c mawk -l traditional

