# minidumper
# Autogenerated from man page /mnt/d/msys64/usr/share/man/man1/minidumper.1
complete -c minidumper -s t -l type
complete -c minidumper -s n -l nokill
complete -c minidumper -s d -l verbose
complete -c minidumper -s h -l help
complete -c minidumper -s q -l quiet
complete -c minidumper -s V -l version -d '   DESCRIPTION'

