# mkgroup
# Autogenerated from man page /mnt/d/msys64/usr/share/man/man1/mkgroup.1
complete -c mkgroup -s d -d and
complete -c mkgroup -o l/-L -d 'options allow you to specify where the information comes from, some domain, o…'
complete -c mkgroup -s L -d 'option, but you dont like the default domain/group separator from /etc/nsswit…'
complete -c mkgroup -s S -d 'option, for instance:'
complete -c mkgroup -s c
complete -c mkgroup -s o -d 'option allows for (unlikely) special cases with multiple machines where the G…'
complete -c mkgroup -s g -d 'option only prints the information for one group.  The'
complete -c mkgroup -s U -d 'option allows you to enumerate the standard UNIX groups on a Samba machine'
complete -c mkgroup -s l -d or

