# mkpasswd
# Autogenerated from man page /mnt/d/msys64/usr/share/man/man1/mkpasswd.1
complete -c mkpasswd -s d -d and
complete -c mkpasswd -o l/-L -d 'options allow you to specify where the information comes from, some domain, o…'
complete -c mkpasswd -s L -d 'option, but you dont like the default domain/group separator from /etc/nsswit…'
complete -c mkpasswd -s S -d 'option, analog to mkgroup'
complete -c mkpasswd -s c
complete -c mkpasswd -s o -d 'option allows for special cases (such as multiple domains) where the UIDs mig…'
complete -c mkpasswd -s p -d 'option causes mkpasswd to use the specified prefix instead of the account hom…'
complete -c mkpasswd -s u -d 'option creates just an entry for the specified user.  The'
complete -c mkpasswd -s U -d 'option allows you to enumerate the standard UNIX users on a Samba machine'
complete -c mkpasswd -s l -d or

