# netplan-rebind
# Autogenerated from man page /usr/share/man/man8/netplan-rebind.8.gz
complete -c netplan-rebind -s h -l help -d 'Print basic help'
complete -c netplan-rebind -l debug -d 'Print debugging output during the process'

