# netplan-status
# Autogenerated from man page /usr/share/man/man8/netplan-status.8.gz
complete -c netplan-status -s h -l help -d 'Print basic help'
complete -c netplan-status -l debug -d 'Print debugging output during the process'
complete -c netplan-status -s a -l all -d 'Show all interface data including inactive'
complete -c netplan-status -l diff -d 'Analyse and display differences between the current system configuration and …'
complete -c netplan-status -l diff-only -d 'Same as --diff but omits all the information that is not a difference'
complete -c netplan-status -l root-dir -d 'Read YAML files from this root instead of /'
complete -c netplan-status -l verbose -d 'Show extra information'
complete -c netplan-status -s f -l format -d 'Output in machine-readable json or yaml format.  SEE ALSO'

