# netplan-ip
# Autogenerated from man page /usr/share/man/man8/netplan-ip.8.gz
complete -c netplan-ip -s h -l help -d 'Print basic help'
complete -c netplan-ip -l debug -d 'Print debugging output during the process'
complete -c netplan-ip -l root-dir -d 'Read YAML files from this root instead of /.  SEE ALSO'

