# netplan-info
# Autogenerated from man page /usr/share/man/man8/netplan-info.8.gz
complete -c netplan-info -s h -l help -d 'Print basic help'
complete -c netplan-info -l debug -d 'Print debugging output during the process'
complete -c netplan-info -l json -d 'Output version and features in JSON format'
complete -c netplan-info -l yaml -d 'Output version and features in YAML format (default).  SEE ALSO'

