# open
# Autogenerated from man page /usr/share/man/man1/open.1.gz
complete -c open -l action -d 'Performs the specified action on the files'
complete -c open -l debug -d 'Turns on extra information to find out what is happening'
complete -c open -l nopager -d 'Ignores any "copiousoutput" directive and sends output to STDOUT'
complete -c open -l norun -d 'Displays the found command without actually executing it'

