# pastebinit
# Autogenerated from man page /usr/share/man/man1/pastebinit.1.gz
complete -c pastebinit -s b
complete -c pastebinit -s i
complete -c pastebinit -s l
complete -c pastebinit -s E
complete -c pastebinit -s h
complete -c pastebinit -s v
complete -c pastebinit -s V
complete -c pastebinit -s a
complete -c pastebinit -s t
complete -c pastebinit -s f
complete -c pastebinit -s j
complete -c pastebinit -s m
complete -c pastebinit -s P
complete -c pastebinit -s u
complete -c pastebinit -s p

