# pg
# Autogenerated from man page /mnt/d/msys64/usr/share/man/man1/pg.1.gz
complete -c pg -s c -d 'Clear the screen before a page is displayed, if the terminfo entry for the te…'
complete -c pg -s e -d 'Do not pause and display . SM (EOF) at the end of a file'
complete -c pg -s f -d 'Do not split long lines'
complete -c pg -s n -d 'Without this option, commands must be terminated by a newline character'
complete -c pg -s p -d 'Instead of the normal prompt R : ,  string is displayed'
complete -c pg -s r -d 'Disallow the shell escape'
complete -c pg -s s -d 'Print messages in  standout mode, if the terminfo entry for the terminal prov…'
complete -c pg -s V -l version -d 'Display version information and exit'
complete -c pg -s h -l help -d 'Display help text and exit'

