# pysetup3.12
# Autogenerated from man page /usr/share/man/man1/pysetup3.12.1.gz
complete -c 'pysetup3.12' -l verbose -s v -d 'run verbosely (default)'
complete -c 'pysetup3.12' -l quiet -s q -d 'run quietly (turns verbosity off)'
complete -c 'pysetup3.12' -l dry-run -s n -d 'don\'t actually do anything'
complete -c 'pysetup3.12' -l help -s h -d 'show detailed help message'
complete -c 'pysetup3.12' -l no-user-cfg -d 'ignore pydistutils. cfg in your home directory'
complete -c 'pysetup3.12' -l version -d 'Display the version'

