# reboot
# Autogenerated from man page /usr/share/man/man8/reboot.8.gz
complete -c reboot -l help
complete -c reboot -l halt
complete -c reboot -s p -l poweroff
complete -c reboot -l reboot
complete -c reboot -s f -l force
complete -c reboot -s w -l wtmp-only
complete -c reboot -s d -l no-wtmp
complete -c reboot -s n -l no-sync
complete -c reboot -l no-wall

