# regtool
# Autogenerated from man page /mnt/d/msys64/usr/share/man/man1/regtool.1
complete -c regtool -s v -d 'option means "verbose"'
complete -c regtool -s q -d 'option supresses error messages, so you can use the exit status of the progra…'
complete -c regtool -s w -d 'option allows you to access the 64 bit view of the registry'
complete -c regtool -s W -d 'option allows you to access the 32 bit view on the registry'
complete -c regtool -s k -d 'option instructs regtool to print only KEYs, and the'
complete -c regtool -s l -d 'option to print only VALUEs.  The'
complete -c regtool -s p -d 'option postfixes a / to each KEY, but leave VALUEs with no postfix'
complete -c regtool -s b -d 'option, data is printed as hex bytes'
complete -c regtool -s n -d 'allows to print the data as a typeless stream of bytes'
complete -c regtool -s x -d 'option allows to print the numbers as hexadecimal values'
complete -c regtool -s d -d or
complete -c regtool -s i -d 'means the value is a 32 bit integer value (REG_DWORD)'
complete -c regtool -s D -d 'means the value is a 32 bit integer value in Big Endian representation (REG_D…'
complete -c regtool -s Q -d 'means the value is a 64 bit integer value (REG_QWORD)'
complete -c regtool -s s -d 'means the value is a string (REG_SZ)'
complete -c regtool -s e -d 'means its an expanding string (REG_EXPAND_SZ) that contains embedded environm…'
complete -c regtool -s m -d 'means its a multi-string (REG_MULTI_SZ)'
complete -c regtool -s K -d 'option to provide an alternate key/value separator character'

