# rename.ul
# Autogenerated from man page /usr/share/man/man1/rename.ul.1.gz
complete -c 'rename.ul' -s s -l symlink
complete -c 'rename.ul' -s v -l verbose
complete -c 'rename.ul' -s n -l no-act
complete -c 'rename.ul' -s a -l all
complete -c 'rename.ul' -s l -l last
complete -c 'rename.ul' -s o -l no-overwrite
complete -c 'rename.ul' -s i -l interactive
complete -c 'rename.ul' -s h -l help
complete -c 'rename.ul' -s V -l version

