# setfacl
# Autogenerated from man page /mnt/d/msys64/usr/share/man/man1/setfacl.1
complete -c setfacl -s f -d 'the section called “POSIX accounts, permission, and security” in the Cygwin U…'
complete -c setfacl -s b -l remove-all -d 'Remove all extended ACL entries'
complete -c setfacl -s k -l remove-default -d 'option to delete all non-standard POSIX permissions'
complete -c setfacl -s x -l delete -d 'Delete one or more specified entries from the files ACL'
complete -c setfacl -l set-file -d 'Take the Acl_entries from ACL_FILE one per line'
complete -c setfacl -s m -l modify -d 'Add or modify one or more specified ACL entries'
complete -c setfacl -s n -l no-mask -d 'Valid in conjunction with -m.  Do not recalculate the effective rights mask'
complete -c setfacl -l mask -d 'Valid in conjunction with -m'
complete -c setfacl -s s -l set -d Like

