# ssp
# Autogenerated from man page /mnt/d/msys64/usr/share/man/man1/ssp.1
complete -c ssp -s d -d 'option to ssp to default to *disabling* profiling'
complete -c ssp -s v
complete -c ssp -s t -d and
complete -c ssp -s c
complete -c ssp -s s
complete -c ssp -s l

