# strace
# Autogenerated from man page /mnt/d/msys64/usr/share/man/man1/strace.1
complete -c strace -s o -d 'option.  With the'
complete -c strace -s w -d 'option, you can start an strace session in a new window, for example: $ strac…'

