# systemd-ask-password-console.path
# Autogenerated from man page /usr/share/man/man8/systemd-ask-password-console.path.8.gz
complete -c 'systemd-ask-password-console.path' -l watch -l console -d or
complete -c 'systemd-ask-password-console.path' -l wall -d 'command line parameters.  SEE ALSO'

