# systemd-ask-password-wall.service
# Autogenerated from man page /usr/share/man/man8/systemd-ask-password-wall.service.8.gz
complete -c 'systemd-ask-password-wall.service' -l watch -l console -d or
complete -c 'systemd-ask-password-wall.service' -l wall -d 'command line parameters.  SEE ALSO'

