# systemd-fsckd.socket
# Autogenerated from man page /usr/share/man/man8/systemd-fsckd.socket.8.gz
complete -c 'systemd-fsckd.socket' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-fsckd.socket' -l version -d 'Print a short version string and exit'

