# systemd-hybrid-sleep.service
# Autogenerated from man page /usr/share/man/man8/systemd-hybrid-sleep.service.8.gz
complete -c 'systemd-hybrid-sleep.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-hybrid-sleep.service' -l version -d 'Print a short version string and exit'

