# systemd-sysext.service
# Autogenerated from man page /usr/share/man/man8/systemd-sysext.service.8.gz
complete -c 'systemd-sysext.service' -l root -d 'Operate relative to the specified root directory, i. e'
complete -c 'systemd-sysext.service' -l force -d 'When merging system extensions into /usr/ and /opt/ for sysext and /etc/ for …'
complete -c 'systemd-sysext.service' -l image-policy -d 'Takes an image policy string as argument, as per systemd. image-policy(7)'
complete -c 'systemd-sysext.service' -l noexec -d 'When merging configuration extensions into /etc/ the "MS_NOEXEC" mount flag i…'
complete -c 'systemd-sysext.service' -l no-reload -d 'When used with merge, unmerge or refresh, do not reload daemon after executin…'
complete -c 'systemd-sysext.service' -l no-pager -d 'Do not pipe output into a pager'
complete -c 'systemd-sysext.service' -l no-legend -d 'Do not print the legend, i. e.  column headers and the footer with hints'
complete -c 'systemd-sysext.service' -l json -d 'Shows output formatted as JSON'
complete -c 'systemd-sysext.service' -l directory -d 'switches and those that the service manager supports via RootDirectory=/RootI…'
complete -c 'systemd-sysext.service' -s h -l help
complete -c 'systemd-sysext.service' -l version

