# systemd-sysctl
# Autogenerated from man page /usr/share/man/man8/systemd-sysctl.8.gz
complete -c systemd-sysctl -l prefix -d 'Only apply rules with the specified prefix. sp Added in version 230'
complete -c systemd-sysctl -l strict -d 'Always return non-zero exit code on failure (including invalid sysctl variabl…'
complete -c systemd-sysctl -l cat-config -d 'Copy the contents of config files to standard output'
complete -c systemd-sysctl -l tldr -d 'Copy the contents of config files to standard output'
complete -c systemd-sysctl -l no-pager -d 'Do not pipe output into a pager'
complete -c systemd-sysctl -s h -l help -d 'Print a short help text and exit'
complete -c systemd-sysctl -l version -d 'Print a short version string and exit'

