# systemd-journald-audit.socket
# Autogenerated from man page /usr/share/man/man8/systemd-journald-audit.socket.8.gz
complete -c 'systemd-journald-audit.socket' -l namespace -d 'switch of journalctl(1) may be used to view the log stream of a specific name…'

