# systemd-pcrlock-firmware-code.service
# Autogenerated from man page /usr/share/man/man8/systemd-pcrlock-firmware-code.service.8.gz
complete -c 'systemd-pcrlock-firmware-code.service' -l raw-description -d 'When displaying the TPM2 event log do not attempt to decode the records to pr…'
complete -c 'systemd-pcrlock-firmware-code.service' -l pcr -d 'Specifies the PCR number to use'
complete -c 'systemd-pcrlock-firmware-code.service' -l nv-index -d 'Specifies to NV index to store the policy in.  Honoured by make-policy'
complete -c 'systemd-pcrlock-firmware-code.service' -l components -d 'Takes a path to read *. pcrlock and *. pcrlock. d/*. pcrlock files from'
complete -c 'systemd-pcrlock-firmware-code.service' -l location -d 'Takes either a string or a colon-separated pair of strings'
complete -c 'systemd-pcrlock-firmware-code.service' -l recovery-pin -d 'Takes a boolean.  Defaults to false.  Honoured by make-policy'
complete -c 'systemd-pcrlock-firmware-code.service' -l pcrlock -d 'Takes a file system path as argument'
complete -c 'systemd-pcrlock-firmware-code.service' -l policy -d 'Takes a file system path as argument'
complete -c 'systemd-pcrlock-firmware-code.service' -l force -d 'If specified with make-policy, the predicted policy will be written to the NV…'
complete -c 'systemd-pcrlock-firmware-code.service' -l json -d 'Shows output formatted as JSON'
complete -c 'systemd-pcrlock-firmware-code.service' -l no-pager -d 'Do not pipe output into a pager'
complete -c 'systemd-pcrlock-firmware-code.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-pcrlock-firmware-code.service' -l version -d 'Print a short version string and exit'
complete -c 'systemd-pcrlock-firmware-code.service' -l tpm2-pcrlock -d 'switches of these tools'
complete -c 'systemd-pcrlock-firmware-code.service' -l pcrs -d 'is specified'

