# systemd-pcrphase-sysinit.service
# Autogenerated from man page /usr/share/man/man8/systemd-pcrphase-sysinit.service.8.gz
complete -c 'systemd-pcrphase-sysinit.service' -l bank -d 'Takes the PCR banks to extend the specified word into'
complete -c 'systemd-pcrphase-sysinit.service' -l pcr -d 'Takes the index of the PCR to extend'
complete -c 'systemd-pcrphase-sysinit.service' -l tpm2-device -d 'Controls which TPM2 device to use'
complete -c 'systemd-pcrphase-sysinit.service' -l graceful -d 'If no TPM2 firmware, kernel subsystem, kernel driver or device support is fou…'
complete -c 'systemd-pcrphase-sysinit.service' -l machine-id -d 'Instead of measuring a word specified on the command line into PCR 11, measur…'
complete -c 'systemd-pcrphase-sysinit.service' -l file-system -d 'Instead of measuring a word specified on the command line into PCR 11, measur…'
complete -c 'systemd-pcrphase-sysinit.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-pcrphase-sysinit.service' -l version -d 'Print a short version string and exit'
complete -c 'systemd-pcrphase-sysinit.service' -l phase -d 'switch)'

