# systemd-bsod
# Autogenerated from man page /usr/share/man/man8/systemd-bsod.8.gz
complete -c systemd-bsod -s h -l help -d 'Print a short help text and exit'
complete -c systemd-bsod -l version -d 'Print a short version string and exit'
complete -c systemd-bsod -s c -l continuous -d 'When specified, systemd-bsod waits continuously for changes in the journal if…'

