# systemd-journald-varlink@.socket
# Autogenerated from man page /usr/share/man/man8/systemd-journald-varlink@.socket.8.gz
complete -c 'systemd-journald-varlink@.socket' -l namespace -d 'switch of journalctl(1) may be used to view the log stream of a specific name…'

