# systemd-suspend-then-hibernate.service
# Autogenerated from man page /usr/share/man/man8/systemd-suspend-then-hibernate.service.8.gz
complete -c 'systemd-suspend-then-hibernate.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-suspend-then-hibernate.service' -l version -d 'Print a short version string and exit'

