# systemd-battery-check
# Autogenerated from man page /usr/share/man/man8/systemd-battery-check.8.gz
complete -c systemd-battery-check -s h -l help -d 'Print a short help text and exit'
complete -c systemd-battery-check -l version -d 'Print a short version string and exit'

