# systemd-pcrextend
# Autogenerated from man page /usr/share/man/man8/systemd-pcrextend.8.gz
complete -c systemd-pcrextend -l bank -d 'Takes the PCR banks to extend the specified word into'
complete -c systemd-pcrextend -l pcr -d 'Takes the index of the PCR to extend'
complete -c systemd-pcrextend -l tpm2-device -d 'Controls which TPM2 device to use'
complete -c systemd-pcrextend -l graceful -d 'If no TPM2 firmware, kernel subsystem, kernel driver or device support is fou…'
complete -c systemd-pcrextend -l machine-id -d 'Instead of measuring a word specified on the command line into PCR 11, measur…'
complete -c systemd-pcrextend -l file-system -d 'Instead of measuring a word specified on the command line into PCR 11, measur…'
complete -c systemd-pcrextend -s h -l help -d 'Print a short help text and exit'
complete -c systemd-pcrextend -l version -d 'Print a short version string and exit'
complete -c systemd-pcrextend -l phase -d 'switch)'

