# systemd-fsckd.service
# Autogenerated from man page /usr/share/man/man8/systemd-fsckd.service.8.gz
complete -c 'systemd-fsckd.service' -s h -l help -d 'Print a short help text and exit'
complete -c 'systemd-fsckd.service' -l version -d 'Print a short version string and exit'

