# systemd-storagetm
# Autogenerated from man page /usr/share/man/man8/systemd-storagetm.8.gz
complete -c systemd-storagetm -l nqn -d 'Takes a string'
complete -c systemd-storagetm -l all -s a -d 'If specified exposes all local block devices via NVMe-TCP, current and future…'
complete -c systemd-storagetm -s h -l help -d 'Print a short help text and exit'
complete -c systemd-storagetm -l version -d 'Print a short version string and exit'

