# toe
# Autogenerated from man page /usr/share/man/man1/toe.1.gz
complete -c toe -s u -d '-a lists entries from all terminal database directories that terminfo would s…'
complete -c toe -s s -d '\\%toe adds a column to the report, showing (like \\%conflict(1)) which entries…'
complete -c toe -s h -d 'writes a heading naming each each directory as it is accessed'
complete -c toe -s U -d 'lists terminal type reverse dependencies in file, a terminfo entry source or …'
complete -c toe -s v -d 'R n ] reports verbose status information to the standard error stream, showin…'
complete -c toe -s a -d 'lists entries from all terminal database directories that terminfo would sear…'
complete -c toe -s V -d 'reports the version of %ncurses associated with this program and exits with a…'

