# update-ca-certificates
# Autogenerated from man page /usr/share/man/man8/update-ca-certificates.8.gz
complete -c update-ca-certificates -s h -l help -d 'Show summary of options'
complete -c update-ca-certificates -s v -l verbose -d 'Be verbose.  Output openssl rehash'
complete -c update-ca-certificates -s f -l fresh -d 'Fresh updates.   Remove symlinks in /etc/ssl/certs directory'
complete -c update-ca-certificates -l certsconf -d 'Change the configuration file.  By default, the file /etc/ca-certificates'
complete -c update-ca-certificates -l certsdir -d 'Change the certificate directory'
complete -c update-ca-certificates -l localcertsdir -d 'Change the local certificate directory'
complete -c update-ca-certificates -l etccertsdir -d 'Change the /etc certificate directory'

