# update-alternatives
# Autogenerated from man page /usr/share/man/man1/update-alternatives.1.gz
complete -c update-alternatives -l altdir -d 'X Item "--altdir directory" Specifies the alternatives directory, when this i…'
complete -c update-alternatives -l admindir -d 'X Item "--admindir directory" Specifies the administrative directory, when th…'
complete -c update-alternatives -l instdir -d 'X Item "--instdir directory" Specifies the installation directory where alter…'
complete -c update-alternatives -l root -d 'X Item "--root directory" Specifies the root directory (since version 1. 20'
complete -c update-alternatives -l log -d 'X Item "--log file" Specifies the log file (since version 1. 15'
complete -c update-alternatives -l force -d 'X Item "--force" Allow replacing or dropping any real file that is installed …'
complete -c update-alternatives -l skip-auto -d 'X Item "--skip-auto" Skip configuration prompt for alternatives which are pro…'
complete -c update-alternatives -l quiet -d 'X Item "--quiet" Do not generate any comments unless errors occur'
complete -c update-alternatives -l verbose -d 'X Item "--verbose" Generate more comments about what is being done'
complete -c update-alternatives -l config -d 'option, update-alternatives will list all of the choices for the link group o…'
complete -c update-alternatives -l auto -d 'option in order to return to the automatic mode (or you can rerun'
complete -c update-alternatives -l set -d 'option instead (see below)'
complete -c update-alternatives -l install -l slave
complete -c update-alternatives -l remove
complete -c update-alternatives -l remove-all
complete -c update-alternatives -l all
complete -c update-alternatives -l display
complete -c update-alternatives -l get-selections
complete -c update-alternatives -l set-selections
complete -c update-alternatives -l query
complete -c update-alternatives -l list
complete -c update-alternatives -l help
complete -c update-alternatives -l version
complete -c update-alternatives -l debug

