# which.debianutils
# Autogenerated from man page /usr/share/man/man1/which.debianutils.1.gz
complete -c 'which.debianutils' -s a -d 'print all matching pathnames of each argument'
complete -c 'which.debianutils' -s s -d 'silently return 0 if all of the executables were found  or 1 otherwise EXIT S…'

