# which
# Autogenerated from man page /usr/share/man/man1/which.1.gz
complete -c which -s a -d 'print all matching pathnames of each argument'
complete -c which -s s -d 'silently return 0 if all of the executables were found  or 1 otherwise EXIT S…'

