# x86_64-linux-gnu-gp-display-src
# Autogenerated from man page /usr/share/man/man1/x86_64-linux-gnu-gp-display-src.1.gz
complete -c x86_64-linux-gnu-gp-display-src -l version -d 'X Item "--version" Print the version number and exit'
complete -c x86_64-linux-gnu-gp-display-src -l help -d 'X Item "--help" Print usage information and exit'
complete -c x86_64-linux-gnu-gp-display-src -o functions -d 'X Item "-functions" List all the functions from the given object'
complete -c x86_64-linux-gnu-gp-display-src -o source -d 'X Item "-source item tag" Show the source code for item in target-file'
complete -c x86_64-linux-gnu-gp-display-src -o disasm -d 'X Item "-disasm item tag" Include the disassembly in the source listing'
complete -c x86_64-linux-gnu-gp-display-src -o outfile

