# x86_64-linux-gnu-gprofng
# Autogenerated from man page /usr/share/man/man1/x86_64-linux-gnu-gprofng.1.gz
complete -c x86_64-linux-gnu-gprofng -l version -d 'X Item "--version" Print the version number and exit'
complete -c x86_64-linux-gnu-gprofng -l help

